### Initial get 
GET http://localhost:3001/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb256YTEzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiR29uemFsbyIsImlhdCI6MTc2MzE1MjQxNCwiZXhwIjoxNzYzMTU5NjE0fQ.yuVA-ZOaQp1Y7I_gpzUEL5bADWi30dPWgmGw5f2s0rs

### Login 
POST http://localhost:3001/api/auth/login
Content-Type: application/json


{
    "email": "test@example.com",
    "password": "prueba"
}


### Service
GET http://localhost:3001/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcwNTMwMjI5LCJleHAiOjE3NzA1Mzc0Mjl9.wwiLJIoRmXCIzLX0_od2r7GW_QMqsJEWxhtb_PZlgXI

### Create Service
POST http://localhost:3001/api/services
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcwNTMwMjI5LCJleHAiOjE3NzA1Mzc0Mjl9.wwiLJIoRmXCIzLX0_od2r7GW_QMqsJEWxhtb_PZlgXI

{
    "name": "Lavado Completo 2",
    "description": "Lavado completo del vehiculo, incluyendo interior y exterior.",
    "price": 120,
    "duration": 90,
    "category": "COMPLETE",
    "userId": 1
}

### Update service 
PUT http://localhost:3001/api/services/50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY0NjIwODU0LCJleHAiOjE3NjQ2MjgwNTR9.oD-WjhV08ff6HH0vLCU4RNzhW4_NTbMHKm_donDHgl4

{
    "name": "Lavado Completo Actualizado",
    "description": "Lavado completo del vehiculo, incluyendo interior y exterior. Ahora con cera.",
    "price": 130,
    "duration": 100,
    "category": "COMPLETE",
    "userId": 1
}

### Get Service by ID
GET http://localhost:3001/api/services/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY1MTUyNjc5LCJleHAiOjE3NjUxNTk4Nzl9.vW6oaD7gu88WFqn3hQO-zAuVHi3fZg2msYldhjo3H_4


### Get Clients
GET http://localhost:3001/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY1MTYyNTQ3LCJleHAiOjE3NjUxNjk3NDd9.L4Rr-BPEcijc5WNskMoF_pMnqU-EMamcakM3e5NViII


### Employees
GET http://localhost:3001/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY1MTYyNTQ3LCJleHAiOjE3NjUxNjk3NDd9.L4Rr-BPEcijc5WNskMoF_pMnqU-EMamcakM3e5NViII


#### Create Employee
POST http://localhost:3001/api/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY0NjIyNzI2LCJleHAiOjE3NjQ2Mjk5MjZ9.3whd_r8PXm-5f25-9qGR4mzxaPZE2qA0Y0t_FlSeMcU

{
    "name": "Juan Perez",
    "entry_time": "08:00",
    "departure_time": "17:00"
}


### Change status 
PATCH http://localhost:3001/api/employees/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY0NjIyNzI2LCJleHAiOjE3NjQ2Mjk5MjZ9.3whd_r8PXm-5f25-9qGR4mzxaPZE2qA0Y0t_FlSeMcU


### Lavados
GET http://localhost:3001/api/washed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY1MTYyNDI4LCJleHAiOjE3NjUxNjk2Mjh9.j3LKRruCsURcoTGK0SOz4Ypbt2vc5G2zxYKvjdnFlnA

### Crear Lavado
POST http://localhost:3001/api/washed
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY1MTYyNDI4LCJleHAiOjE3NjUxNjk2Mjh9.j3LKRruCsURcoTGK0SOz4Ypbt2vc5G2zxYKvjdnFlnA


{
    "serviceId": 2,
    "employeeId": 1,
    "clientId": 1,
    "details": "Lavar con cera adicional",
    "notify": true
}


### UPDATE STATUS LAVADO
PATCH http://localhost:3001/api/washed/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJHb256YWxvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY5MzkzNzI0LCJleHAiOjE3Njk0MDA5MjR9.473yeCpJZFFG-Q8Sa-2q8jmqkmfJDubWATzo3LDn6b8

{
    "status": "COMPLETED"
}

