
### Initial get
GET http://localhost:3001

### Auth
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "prueba123456"
}

### Get all services
GET http://localhost:3001/api/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNjk4ODgzLCJpYXQiOjE3NjE2OTUyODMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNjk1MjgzfV0sInNlc3Npb25faWQiOiJjYzIzNDI4My02ZWZlLTRjNjgtYTgyNS03MmUyMDExOThmYTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.AHVlq1lxeZnKqPwTbvUIrCHsnWNqox-ABsLK0-PIZY4

### Get service by ID
GET http://localhost:3001/api/services/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNjk4ODgzLCJpYXQiOjE3NjE2OTUyODMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNjk1MjgzfV0sInNlc3Npb25faWQiOiJjYzIzNDI4My02ZWZlLTRjNjgtYTgyNS03MmUyMDExOThmYTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.AHVlq1lxeZnKqPwTbvUIrCHsnWNqox-ABsLK0-PIZY4

### Create a new service
POST http://localhost:3001/api/services
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNjk4ODgzLCJpYXQiOjE3NjE2OTUyODMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNjk1MjgzfV0sInNlc3Npb25faWQiOiJjYzIzNDI4My02ZWZlLTRjNjgtYTgyNS03MmUyMDExOThmYTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.AHVlq1lxeZnKqPwTbvUIrCHsnWNqox-ABsLK0-PIZY4

{
    "name": "Nuevo Servicio",
    "price": 150.00,
    "duration": 60,
    "category": "basic"

}

### Delete a service
DELETE http://localhost:3001/api/services/41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNjk4ODgzLCJpYXQiOjE3NjE2OTUyODMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNjk1MjgzfV0sInNlc3Npb25faWQiOiJjYzIzNDI4My02ZWZlLTRjNjgtYTgyNS03MmUyMDExOThmYTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.AHVlq1lxeZnKqPwTbvUIrCHsnWNqox-ABsLK0-PIZY4

### Update a service
PUT http://localhost:3001/api/services/43
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNjk4ODgzLCJpYXQiOjE3NjE2OTUyODMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNjk1MjgzfV0sInNlc3Npb25faWQiOiJjYzIzNDI4My02ZWZlLTRjNjgtYTgyNS03MmUyMDExOThmYTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.AHVlq1lxeZnKqPwTbvUIrCHsnWNqox-ABsLK0-PIZY4

{
    "name": "Servicio actualizado"
}

### Get all clients
GET http://localhost:3001/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlkrVmwzVjMyZ0VML3dXNVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2Vsam1vZmVsZW9ia3hqZ2d4eGdhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MGU3OTg0Ny0yMDdlLTRiNGEtOTBkNi0yZDc0OGQyNmMzYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYxNzA1MTI0LCJpYXQiOjE3NjE3MDE1MjQsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYxNzAxNTI0fV0sInNlc3Npb25faWQiOiJjMDMwMGU1MC0wNTNkLTQ5NDItYjE0Yy1iYzc2YTRhZmYwY2IiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.HE2SUwgHFEcIA-4feQ8Ypai1aLhIwd5dKHb_Xu8Lito
